ethereum_rpc   = "http://154.12.116.22:9545/"
drosera_rpc    = "https://relay.hoodi.drosera.io"
eth_chain_id   = 560048
drosera_address= "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.vaulttvldrop]
path = "out/VaultTVLDropTrap.sol/VaultTVLDropTrap.json"
response_contract = "0x879615792FeD679F3bD18eBB33990cF1cBBcf79C"
response_function = "handleVaultDrop(string)"
cooldown_period_blocks = 10
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0x8e169f2F85F506080769fe484c659f3F154144b6"]
address = "0x0900AAc4A8a624Da83AbC14542E1BD371D20726a"
