# Network config
ethereum_rpc    = "${RPC}"               # e.g. http://127.0.0.1:8545
drosera_rpc     = "https://relay.hoodi.drosera.io"
eth_chain_id    = ${CHAIN_ID}            # e.g. 560048
drosera_address = "${DROSERA_ADDR}"

[traps]
[traps.vaulttvldrop]
path                    = "out/VaultTVLDropTrap.sol/VaultTVLDropTrap.json"
response_contract       = "${RESP}"      # <- set after deploying VaultTVLResponse
response_function       = "handleVaultDrop(string)"
cooldown_period_blocks  = 10
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size       = 10
private_trap            = true
whitelist               = ["${YOUR_EOA}"] #YOUR_OPERATOR_WALLET_ADDRESS
